[package]
name = "cargo-rtic-scope"
version = "0.1.0"
authors = ["Viktor Sonesten <v@tmplt.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://rtic-scope.github.io"
repository = "https://github.com/rtic-scope/cargo-rtic-scope"
description = "RTIC Scope backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
clap = "2.33"
cargo_metadata = "0.11"
syn = "1"
proc-macro2 = "1"
quote = "1"
nix = "0.21.0"
include_dir = "0.6.1"
libloading = "0.7"
rtic-syntax = "=0.5.0-alpha.3"
serde = "1"
serde_json = "1"
rtic-scope-api = { version = "0.1.0-alpha", path = "../rtic-scope-api/" }
tempfile = "3"
ctrlc = "3"
thiserror = "1"
colored = "2"

[dependencies.probe-rs]
version = "0.11"
git = "https://github.com/rtic-scope/probe-rs.git"
rev = "b82c4a4845240833a76e299f4775680d04a87692"

[dependencies.probe-rs-cli-util]
version = "0.11"
git = "https://github.com/rtic-scope/probe-rs.git"
rev = "b82c4a4845240833a76e299f4775680d04a87692"

[dependencies.anyhow]
version = "1"
features = ["backtrace"]

[dependencies.serialport]
version = "4"
default-features = false # we don't need libudev functionalities

[dependencies.git2]
version = "0.13"
default-features = false

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.itm-decode]
version = "0.4.0-alpha"
features = ["serde"]
